image: node:12-alpine

cache:
  paths:
    - node_modules/

deploy_test:
  stage: deploy
  environment:
    name: test
  only:
    - develop
  script:
    - npm install -g firebase-tools
    - npm install
    - REACT_APP_API_HOST=$REACT_APP_API_HOST REACT_APP_FB_APP_ID=$REACT_APP_FB_APP_ID npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY

deploy_production:
  stage: deploy
  environment:
    name: production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - REACT_APP_API_HOST=$REACT_APP_API_HOST REACT_APP_FB_APP_ID=$REACT_APP_FB_APP_ID npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
